import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { ArchetypeDoc, BehaviorDoc, ComponentDoc, OntologyBundle } from "./types";

// Minimal hand-written JSON-LD → TypeScript. No template engine; plain string
// concatenation keeps dev-time diff noise small.

const HEADER = `// This file is generated by src/ontology/codegen.ts. Do not edit by hand.
// Run: npm run ontology:codegen

`;

function tsTypeFromField(type: string): string {
  if (type === "int" || type === "float") return "number";
  if (type === "string") return "string";
  if (type === "boolean") return "boolean";
  if (type.startsWith("map<") && type.endsWith(">")) {
    const inner = type.slice(4, -1); // string,float
    const parts = inner.split(",").map((s) => s.trim());
    const keyT = parts[0] === "string" ? "string" : "string";
    const valT = tsTypeFromField(parts[1] ?? "float");
    return `Record<${keyT}, ${valT}>`;
  }
  if (type.startsWith("list<") && type.endsWith(">")) {
    const inner = type.slice(5, -1);
    return `${tsTypeFromField(inner)}[]`;
  }
  if (type.includes("|")) {
    return type
      .split("|")
      .map((t) => tsTypeFromField(t.trim()))
      .join(" | ");
  }
  if (type === "null") return "null";
  // Default: treat as an opaque nominal type (user-defined).
  return type;
}

export function generateComponentTypes(components: ComponentDoc[]): string {
  const parts: string[] = [HEADER];
  for (const c of components) {
    const fields = c.fields
      .map((f) => `  ${f.name}: ${tsTypeFromField(f.type)};`)
      .join("\n");
    parts.push(
      `/** ${c.description} (${c.category}, ${c.domain}) */\nexport interface ${c.name} {\n${fields}\n}\n`,
    );
  }
  parts.push(
    `export type ComponentId =\n${components
      .map((c) => `  | "${c["@id"]}"`)
      .join("\n") || `  | never`};\n`,
  );
  return parts.join("\n");
}

export function generateBehaviorMeta(behaviors: BehaviorDoc[]): string {
  const parts: string[] = [HEADER];
  parts.push(`export type BehaviorStateMachine = {
  states: string[];
  initial: string;
  transitions: Array<{ from: string; to: string; on: string }>;
};

export type BehaviorMeta = {
  id: string;
  name: string;
  domain: string;
  description: string;
  required_components: string[];
  reads: string[];
  writes: string[];
  actions: Array<{ name: string; input?: Record<string, string>; effects?: string[] }>;
  state_machine: BehaviorStateMachine;
};

export const BEHAVIORS: Record<string, BehaviorMeta> = {
`);
  for (const b of behaviors) {
    parts.push(`  ${b.name}: ${JSON.stringify(
      {
        id: b["@id"],
        name: b.name,
        domain: b.domain,
        description: b.description,
        required_components: b.required_components,
        reads: b.reads ?? [],
        writes: b.writes ?? [],
        actions: b.actions,
        state_machine: b.state_machine,
      },
      null,
      2,
    )
      .split("\n")
      .map((l, i) => (i === 0 ? l : "  " + l))
      .join("\n")},\n`);
  }
  parts.push(`};\n`);
  return parts.join("");
}

export function generateArchetypeMeta(archetypes: ArchetypeDoc[]): string {
  const parts: string[] = [HEADER];
  parts.push(`export type ArchetypeMeta = {
  id: string;
  name: string;
  scale: "micro" | "meso" | "macro";
  components: string[];
  behaviors: string[];
};

export const ARCHETYPES: Record<string, ArchetypeMeta> = {
`);
  for (const a of archetypes) {
    parts.push(`  ${a.name}: ${JSON.stringify(
      { id: a["@id"], name: a.name, scale: a.scale, components: a.components, behaviors: a.behaviors },
      null,
      2,
    )
      .split("\n")
      .map((l, i) => (i === 0 ? l : "  " + l))
      .join("\n")},\n`);
  }
  parts.push(`};\n`);
  return parts.join("");
}

export async function writeGeneratedOntology(bundle: OntologyBundle, outDir: string): Promise<void> {
  await mkdir(outDir, { recursive: true });
  await writeFile(join(outDir, "components.ts"), generateComponentTypes(bundle.components), "utf-8");
  await writeFile(join(outDir, "behaviors.ts"), generateBehaviorMeta(bundle.behaviors), "utf-8");
  await writeFile(join(outDir, "archetypes.ts"), generateArchetypeMeta(bundle.archetypes), "utf-8");
}
